export const erc20Abi = [
  {
    type: "function",
    name: "name",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "nonces",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "decimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "mint",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
] as const;

export const marketFactoryAbi = [
  {
    type: "function",
    name: "createMarket",
    stateMutability: "nonpayable",
    inputs: [
      { name: "settlementToken", type: "address" },
      { name: "metadataHash", type: "bytes32" },
      { name: "metadataURI", type: "string" },
      { name: "outcomes", type: "string[]" },
      { name: "lockTime", type: "uint256" },
      { name: "resolutionTime", type: "uint256" },
      { name: "noWinnersPolicy", type: "uint8" },
      { name: "categoryId", type: "bytes32" },
    ],
    outputs: [{ name: "marketId", type: "uint256" }],
  },
  {
    type: "function",
    name: "createMarketWithPermit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "settlementToken", type: "address" },
      { name: "metadataHash", type: "bytes32" },
      { name: "metadataURI", type: "string" },
      { name: "outcomes", type: "string[]" },
      { name: "lockTime", type: "uint256" },
      { name: "resolutionTime", type: "uint256" },
      { name: "noWinnersPolicy", type: "uint8" },
      { name: "categoryId", type: "bytes32" },
      { name: "permitData", type: "tuple", components: [
        { name: "value", type: "uint256" }, { name: "deadline", type: "uint256" },
        { name: "v", type: "uint8" }, { name: "r", type: "bytes32" }, { name: "s", type: "bytes32" },
      ] },
    ],
    outputs: [{ name: "marketId", type: "uint256" }],
  },
  {
    type: "function",
    name: "placeBet",
    stateMutability: "nonpayable",
    inputs: [
      { name: "marketId", type: "uint256" },
      { name: "outcome", type: "uint8" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "placeBetWithPermit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "marketId", type: "uint256" }, { name: "outcome", type: "uint8" },
      { name: "amount", type: "uint256" },
      { name: "permitData", type: "tuple", components: [
        { name: "value", type: "uint256" }, { name: "deadline", type: "uint256" },
        { name: "v", type: "uint8" }, { name: "r", type: "bytes32" }, { name: "s", type: "bytes32" },
      ] },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "placeBetBySig",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "authorization",
        type: "tuple",
        components: [
          { name: "bettor", type: "address" },
          { name: "marketId", type: "uint256" },
          { name: "outcome", type: "uint8" },
          { name: "amount", type: "uint256" },
          { name: "nonce", type: "uint256" },
          { name: "deadline", type: "uint256" },
          { name: "authorizedRelayer", type: "address" },
        ],
      },
      { name: "signature", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "nonces",
    stateMutability: "view",
    inputs: [{ name: "bettor", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "invalidateNonce",
    stateMutability: "nonpayable",
    inputs: [{ name: "newNonce", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "hashBetAuthorization",
    stateMutability: "view",
    inputs: [
      {
        name: "authorization",
        type: "tuple",
        components: [
          { name: "bettor", type: "address" },
          { name: "marketId", type: "uint256" },
          { name: "outcome", type: "uint8" },
          { name: "amount", type: "uint256" },
          { name: "nonce", type: "uint256" },
          { name: "deadline", type: "uint256" },
          { name: "authorizedRelayer", type: "address" },
        ],
      },
    ],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "domainSeparatorV4",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "resolveMarket",
    stateMutability: "nonpayable",
    inputs: [
      { name: "marketId", type: "uint256" },
      { name: "winningOutcome", type: "uint8" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "claimReward",
    stateMutability: "nonpayable",
    inputs: [{ name: "marketId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "claimRefund",
    stateMutability: "nonpayable",
    inputs: [{ name: "marketId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "totalStakeByUser",
    stateMutability: "view",
    inputs: [
      { name: "marketId", type: "uint256" },
      { name: "user", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "event",
    name: "MarketCreated",
    inputs: [
      { name: "marketId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "settlementToken", type: "address", indexed: true },
      { name: "metadataHash", type: "bytes32", indexed: false },
      { name: "metadataURI", type: "string", indexed: false },
      { name: "categoryId", type: "bytes32", indexed: false },
      { name: "mode", type: "uint8", indexed: false },
      { name: "riskLevel", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BetPlaced",
    inputs: [
      { name: "marketId", type: "uint256", indexed: true },
      { name: "user", type: "address", indexed: true },
      { name: "outcome", type: "uint8", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "MarketResolved",
    inputs: [
      { name: "marketId", type: "uint256", indexed: true },
      { name: "winningOutcome", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "FeesAccrued",
    inputs: [
      { name: "marketId", type: "uint256", indexed: true },
      { name: "admin", type: "address", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "adminFee", type: "uint256", indexed: false },
      { name: "creatorFee", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RewardClaimed",
    inputs: [
      { name: "marketId", type: "uint256", indexed: true },
      { name: "user", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RefundClaimed",
    inputs: [
      { name: "marketId", type: "uint256", indexed: true },
      { name: "user", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SignedBetExecuted",
    inputs: [
      { name: "marketId", type: "uint256", indexed: true },
      { name: "bettor", type: "address", indexed: true },
      { name: "relayer", type: "address", indexed: true },
      { name: "outcome", type: "uint8", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "nonce", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "NonceInvalidated",
    inputs: [
      { name: "bettor", type: "address", indexed: true },
      { name: "oldNonce", type: "uint256", indexed: false },
      { name: "newNonce", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BondCalculated",
    inputs: [
      { name: "entityType", type: "bytes32", indexed: true },
      { name: "entityId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "requiredBond", type: "uint256", indexed: false },
      { name: "reasonFlags", type: "uint16", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BondLocked",
    inputs: [
      { name: "entityType", type: "bytes32", indexed: true },
      { name: "entityId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BondReleased",
    inputs: [
      { name: "entityType", type: "bytes32", indexed: true },
      { name: "entityId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BondSlashed",
    inputs: [
      { name: "entityType", type: "bytes32", indexed: true },
      { name: "entityId", type: "uint256", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "reasonHash", type: "bytes32", indexed: false },
    ],
  },
] as const;

export const creationBondPolicyAbi = [
  {
    type: "function",
    name: "previewBond",
    stateMutability: "view",
    inputs: [
      {
        name: "context",
        type: "tuple",
        components: [
          { name: "entityType", type: "uint8" },
          { name: "mode", type: "uint8" },
          { name: "creatorTier", type: "uint8" },
          { name: "categoryRisk", type: "uint8" },
          { name: "reputation", type: "uint8" },
          { name: "expectedVolume", type: "uint256" },
          { name: "disputeCount", type: "uint256" },
          { name: "fraudCount", type: "uint256" },
        ],
      },
    ],
    outputs: [
      { name: "amount", type: "uint256" },
      { name: "reasonFlags", type: "uint16" },
    ],
  },
] as const;

export const creationBondContextResolverAbi = [
  {
    type: "function",
    name: "previewBond",
    stateMutability: "view",
    inputs: [
      { name: "policy", type: "address" },
      { name: "creator", type: "address" },
      { name: "entityType", type: "uint8" },
      { name: "categoryId", type: "bytes32" },
      { name: "expectedVolume", type: "uint256" },
    ],
    outputs: [
      { name: "amount", type: "uint256" },
      { name: "reasonFlags", type: "uint16" },
    ],
  },
  {
    type: "function",
    name: "resolve",
    stateMutability: "view",
    inputs: [
      { name: "creator", type: "address" },
      { name: "entityType", type: "uint8" },
      { name: "categoryId", type: "bytes32" },
      { name: "expectedVolume", type: "uint256" },
    ],
    outputs: [
      {
        name: "context",
        type: "tuple",
        components: [
          { name: "entityType", type: "uint8" },
          { name: "mode", type: "uint8" },
          { name: "creatorTier", type: "uint8" },
          { name: "categoryRisk", type: "uint8" },
          { name: "reputation", type: "uint8" },
          { name: "expectedVolume", type: "uint256" },
          { name: "disputeCount", type: "uint256" },
          { name: "fraudCount", type: "uint256" },
        ],
      },
    ],
  },
] as const;

export const challengeFactoryAbi = [
  {
    type: "function",
    name: "challenges",
    stateMutability: "view",
    inputs: [{ name: "challengeId", type: "uint256" }],
    outputs: [
      { name: "creator", type: "address" },
      { name: "executor", type: "address" },
      { name: "settlementToken", type: "address" },
      { name: "rulesHash", type: "bytes32" },
      { name: "metadataURI", type: "string" },
      { name: "liveStreamURI", type: "string" },
      { name: "rewardPool", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "state", type: "uint8" },
      { name: "evidenceHash", type: "bytes32" },
      { name: "evidenceURI", type: "string" },
      { name: "categoryId", type: "bytes32" },
      { name: "mode", type: "uint8" },
      { name: "riskLevel", type: "uint8" },
    ],
  },
  {
    type: "function",
    name: "createChallenge",
    stateMutability: "nonpayable",
    inputs: [
      { name: "settlementToken", type: "address" },
      { name: "rewardPool", type: "uint256" },
      { name: "rulesHash", type: "bytes32" },
      { name: "metadataURI", type: "string" },
      { name: "deadline", type: "uint256" },
      { name: "categoryId", type: "bytes32" },
    ],
    outputs: [{ name: "challengeId", type: "uint256" }],
  },
  {
    type: "function",
    name: "createChallengeWithPermit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "settlementToken", type: "address" }, { name: "rewardPool", type: "uint256" },
      { name: "rulesHash", type: "bytes32" }, { name: "metadataURI", type: "string" },
      { name: "deadline", type: "uint256" }, { name: "categoryId", type: "bytes32" },
      { name: "permitData", type: "tuple", components: [
        { name: "value", type: "uint256" }, { name: "deadline", type: "uint256" },
        { name: "v", type: "uint8" }, { name: "r", type: "bytes32" }, { name: "s", type: "bytes32" },
      ] },
    ],
    outputs: [{ name: "challengeId", type: "uint256" }],
  },
  {
    type: "function",
    name: "fundingModelByChallenge",
    stateMutability: "view",
    inputs: [{ name: "challengeId", type: "uint256" }],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "rewardEscrowedByChallenge",
    stateMutability: "view",
    inputs: [{ name: "challengeId", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "sponsorOf",
    stateMutability: "view",
    inputs: [{ name: "challengeId", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "performerOf",
    stateMutability: "view",
    inputs: [{ name: "challengeId", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "acceptChallenge",
    stateMutability: "nonpayable",
    inputs: [
      { name: "challengeId", type: "uint256" },
      { name: "liveStreamURI", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "acceptChallengeWithPermit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "challengeId", type: "uint256" }, { name: "liveStreamURI", type: "string" },
      { name: "permitData", type: "tuple", components: [
        { name: "value", type: "uint256" }, { name: "deadline", type: "uint256" },
        { name: "v", type: "uint8" }, { name: "r", type: "bytes32" }, { name: "s", type: "bytes32" },
      ] },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "updateLiveStreamURI",
    stateMutability: "nonpayable",
    inputs: [
      { name: "challengeId", type: "uint256" },
      { name: "liveStreamURI", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "submitEvidence",
    stateMutability: "nonpayable",
    inputs: [
      { name: "challengeId", type: "uint256" },
      { name: "evidenceHash", type: "bytes32" },
      { name: "evidenceURI", type: "string" },
      { name: "liveStreamURI", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "proposeResolution",
    stateMutability: "nonpayable",
    inputs: [
      { name: "challengeId", type: "uint256" },
      { name: "executorSucceeded", type: "bool" },
      { name: "evidenceHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "confirmResolution",
    stateMutability: "nonpayable",
    inputs: [
      { name: "challengeId", type: "uint256" },
      { name: "executorSucceeded", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "disputeResolution",
    stateMutability: "nonpayable",
    inputs: [
      { name: "challengeId", type: "uint256" },
      { name: "reasonHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "finalizeUndisputed",
    stateMutability: "nonpayable",
    inputs: [{ name: "challengeId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "resolveDispute",
    stateMutability: "nonpayable",
    inputs: [
      { name: "challengeId", type: "uint256" },
      { name: "executorSucceeded", type: "bool" },
      { name: "reasonHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "resolveEarly",
    stateMutability: "nonpayable",
    inputs: [
      { name: "challengeId", type: "uint256" },
      { name: "executorSucceeded", type: "bool" },
      { name: "reasonHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "resolutionWindowFor",
    stateMutability: "view",
    inputs: [{ name: "challengeId", type: "uint256" }],
    outputs: [{ name: "", type: "uint64" }],
  },
  {
    type: "function",
    name: "disputeBondFor",
    stateMutability: "view",
    inputs: [{ name: "challengeId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "setStandardResolutionWindow",
    stateMutability: "nonpayable",
    inputs: [{ name: "nextWindow", type: "uint64" }],
    outputs: [],
  },
  {
    type: "function",
    name: "resolveChallenge",
    stateMutability: "nonpayable",
    inputs: [
      { name: "challengeId", type: "uint256" },
      { name: "executorSucceeded", type: "bool" },
      { name: "slashCreatorBond", type: "bool" },
      { name: "slashExecutorBond", type: "bool" },
      { name: "reasonHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelChallenge",
    stateMutability: "nonpayable",
    inputs: [
      { name: "challengeId", type: "uint256" },
      { name: "reasonHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "confirmFraud",
    stateMutability: "nonpayable",
    inputs: [
      { name: "challengeId", type: "uint256" },
      { name: "offender", type: "address" },
      { name: "reasonHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "ChallengeCreated",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "rewardPool", type: "uint256", indexed: false },
      { name: "rulesHash", type: "bytes32", indexed: false },
      { name: "categoryId", type: "bytes32", indexed: false },
      { name: "mode", type: "uint8", indexed: false },
      { name: "riskLevel", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ChallengeAccepted",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "executor", type: "address", indexed: true },
      { name: "executorBond", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ChallengeFundingModelSelected",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "fundingModel", type: "uint8", indexed: false },
      { name: "performer", type: "address", indexed: true },
      { name: "sponsor", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "ChallengeRewardFunded",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "sponsor", type: "address", indexed: true },
      { name: "rewardPool", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ChallengeLiveStreamUpdated",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "actor", type: "address", indexed: true },
      { name: "liveStreamURI", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ChallengeEvidenceSubmitted",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "executor", type: "address", indexed: true },
      { name: "evidenceHash", type: "bytes32", indexed: false },
      { name: "evidenceURI", type: "string", indexed: false },
      { name: "liveStreamURI", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ChallengeResolved",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "winner", type: "address", indexed: true },
      { name: "executorSucceeded", type: "bool", indexed: false },
      { name: "rewardPayout", type: "uint256", indexed: false },
      { name: "adminFee", type: "uint256", indexed: false },
      { name: "creatorFee", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ChallengeCancelled",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "reasonHash", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ChallengeFraudConfirmed",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "offender", type: "address", indexed: true },
      { name: "reasonHash", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ResolutionWindowUpdated",
    inputs: [
      { name: "oldWindow", type: "uint64", indexed: false },
      { name: "newWindow", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ChallengeResolutionProposed",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "proposer", type: "address", indexed: true },
      { name: "executorSucceeded", type: "bool", indexed: false },
      { name: "evidenceHash", type: "bytes32", indexed: false },
      { name: "disputeDeadline", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ChallengeResolutionConfirmed",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "confirmer", type: "address", indexed: true },
      { name: "executorSucceeded", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ChallengeResolutionDisputed",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "disputant", type: "address", indexed: true },
      { name: "bondAmount", type: "uint256", indexed: false },
      { name: "reasonHash", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ChallengeDisputeResolved",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "executorSucceeded", type: "bool", indexed: false },
      { name: "disputeSucceeded", type: "bool", indexed: false },
      { name: "reasonHash", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ChallengeResolvedEarly",
    inputs: [
      { name: "challengeId", type: "uint256", indexed: true },
      { name: "executorSucceeded", type: "bool", indexed: false },
      { name: "reasonHash", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BondCalculated",
    inputs: [
      { name: "entityType", type: "bytes32", indexed: true },
      { name: "entityId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "requiredBond", type: "uint256", indexed: false },
      { name: "reasonFlags", type: "uint16", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BondLocked",
    inputs: [
      { name: "entityType", type: "bytes32", indexed: true },
      { name: "entityId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
] as const;

export const bountyFactoryAbi = [
  {
    type: "function",
    name: "createBounty",
    stateMutability: "nonpayable",
    inputs: [
      { name: "settlementToken", type: "address" },
      { name: "rewardPool", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "rulesHash", type: "bytes32" },
      { name: "metadataURI", type: "string" },
      { name: "categoryId", type: "bytes32" },
    ],
    outputs: [{ name: "bountyId", type: "uint256" }],
  },
  {
    type: "function",
    name: "createBountyWithPermit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "settlementToken", type: "address" }, { name: "rewardPool", type: "uint256" },
      { name: "deadline", type: "uint256" }, { name: "rulesHash", type: "bytes32" },
      { name: "metadataURI", type: "string" }, { name: "categoryId", type: "bytes32" },
      { name: "permitData", type: "tuple", components: [
        { name: "value", type: "uint256" }, { name: "deadline", type: "uint256" },
        { name: "v", type: "uint8" }, { name: "r", type: "bytes32" }, { name: "s", type: "bytes32" },
      ] },
    ],
    outputs: [{ name: "bountyId", type: "uint256" }],
  },
  {
    type: "function",
    name: "bounties",
    stateMutability: "view",
    inputs: [{ name: "bountyId", type: "uint256" }],
    outputs: [
      { name: "creator", type: "address" },
      { name: "settlementToken", type: "address" },
      { name: "rewardPool", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "rulesHash", type: "bytes32" },
      { name: "metadataURI", type: "string" },
      { name: "state", type: "uint8" },
      { name: "categoryId", type: "bytes32" },
      { name: "mode", type: "uint8" },
      { name: "riskLevel", type: "uint8" },
    ],
  },
  {
    type: "function",
    name: "rewardEscrowByBounty",
    stateMutability: "view",
    inputs: [{ name: "bountyId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "recoveryVault",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "setRecoveryVault",
    stateMutability: "nonpayable",
    inputs: [{ name: "nextRecoveryVault", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "submit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "bountyId", type: "uint256" },
      { name: "submissionHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "submitEvidence",
    stateMutability: "nonpayable",
    inputs: [
      { name: "bountyId", type: "uint256" },
      { name: "submissionHash", type: "bytes32" },
      { name: "evidenceURI", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "resolveBounty",
    stateMutability: "nonpayable",
    inputs: [
      { name: "bountyId", type: "uint256" },
      { name: "winners", type: "address[]" },
      { name: "amounts", type: "uint256[]" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelBounty",
    stateMutability: "nonpayable",
    inputs: [
      { name: "bountyId", type: "uint256" },
      { name: "reasonHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "emergencyRecoverBounty",
    stateMutability: "nonpayable",
    inputs: [
      { name: "bountyId", type: "uint256" },
      { name: "incidentHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "BountyCreated",
    inputs: [
      { name: "bountyId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "rewardPool", type: "uint256", indexed: false },
      { name: "rulesHash", type: "bytes32", indexed: false },
      { name: "categoryId", type: "bytes32", indexed: false },
      { name: "mode", type: "uint8", indexed: false },
      { name: "riskLevel", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SubmissionCreated",
    inputs: [
      { name: "bountyId", type: "uint256", indexed: true },
      { name: "submitter", type: "address", indexed: true },
      { name: "submissionHash", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "SubmissionEvidenceCreated",
    inputs: [
      { name: "bountyId", type: "uint256", indexed: true },
      { name: "submitter", type: "address", indexed: true },
      { name: "submissionHash", type: "bytes32", indexed: false },
      { name: "evidenceURI", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BountyResolved",
    inputs: [
      { name: "bountyId", type: "uint256", indexed: true },
      { name: "winners", type: "address[]", indexed: false },
      { name: "amounts", type: "uint256[]", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BountyCancelled",
    inputs: [
      { name: "bountyId", type: "uint256", indexed: true },
      { name: "reasonHash", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RecoveryVaultUpdated",
    inputs: [
      { name: "oldVault", type: "address", indexed: true },
      { name: "newVault", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "EmergencyBountyRecovered",
    inputs: [
      { name: "bountyId", type: "uint256", indexed: true },
      { name: "token", type: "address", indexed: true },
      { name: "recoveryVault", type: "address", indexed: true },
      { name: "rewardAmount", type: "uint256", indexed: false },
      { name: "bondAmount", type: "uint256", indexed: false },
      { name: "incidentHash", type: "bytes32", indexed: false },
      { name: "securityAdmin", type: "address", indexed: false },
    ],
  },
] as const;

export const bountyRecoveryVaultAbi = [
  {
    type: "function",
    name: "coldWallet",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "SECURITY_ADMIN_ROLE",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "recoverToColdWallet",
    stateMutability: "nonpayable",
    inputs: [
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "incidentHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "EmergencyLiquidityRecovered",
    inputs: [
      { name: "token", type: "address", indexed: true },
      { name: "coldWallet", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "incidentHash", type: "bytes32", indexed: true },
      { name: "securityAdmin", type: "address", indexed: false },
    ],
  },
] as const;
