packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - bufferutil
  - esbuild
  - keccak
  - secp256k1
  - sharp
  - utf-8-validate
allowBuilds:
  bufferutil: true
  esbuild: true
  keccak: true
  protobufjs: true
  secp256k1: true
  sharp: true
  tiny-secp256k1: true
  utf-8-validate: true
